baseURL = 'https://zjackie.ink/'
locale = 'zh-CN'
title = 'ZJACKIE.INK'
theme = 'PaperMod'
copyright = '&copy; 2026 Jackie · Content licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'